FROM golang:latest
RUN mkdir -p /go/src/github.com/dbubel/barrenschat-api
ADD . /go/src/github.com/dbubel/barrenschat-api
WORKDIR /go/src/github.com/dbubel/barrenschat-api
#RUN CGO_ENABLED=0 go build -a -v -ldflags '-extldflags "-static"' main.go
RUN go build -v main.go
ENTRYPOINT [ "./main" ]

