FROM golang:1.9.3

RUN mkdir -p /go/src/github.com/engineerbeard/barrenschat2
ADD . /go/src/github.com/engineerbeard/barrenschat2
WORKDIR /go/src/github.com/engineerbeard/barrenschat2
CMD go test -v -race $(go list ./... | grep -v /vendor/)
    