version: '2'
services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    # volumes:
    # - ./data:/data

  barrenschat-api-1:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.run
    environment:
      - NAME="BChatBackend1"

  barrenschat-api-2:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.run
    environment:
      - NAME=BChatBackend2

  load-balancer:
    depends_on:
      - barrenschat-api-2
      - barrenschat-api-1
    build:
      context: .
      dockerfile: Dockerfile.nginx.dev
    ports:
      - "80:80"
      

