version: '2'
services:
  redis:
    image: redis:latest

  barrenschat-api-1:
    depends_on:
      - redis
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.run
    environment:
      - NAME="Instance 1"

  barrenschat-api-2:
    depends_on:
      - redis
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.run
    environment:
      - NAME="Instance 2"

  load-balancer:
    depends_on:
      - barrenschat-api-2
      - barrenschat-api-1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"

      