version: '2'
services:
  # redis:
  #   image: redis:alpine

  barrenschat-api-1:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.run
    environment:
      - NAME="Instance 1"

  barrenschat-api-2:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.run
    environment:
      - NAME="Instance 2"

  # barrenschat-api-3:
  #   # restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.run
  #   environment:
  #     - NAME="Instance 3"
  # barrenschat-api-4:
  #   # restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.run
  #   environment:
  #     - NAME="Instance 4"

  load-balancer:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"