FROM golang:1.10.0-alpine3.7

RUN mkdir -p /go/src/github.com/engineerbeard/barrenschat-api
ADD . /go/src/github.com/engineerbeard/barrenschat-api
WORKDIR /go/src/github.com/engineerbeard/barrenschat-api
RUN go build main.go
ENTRYPOINT [ "./main" ]

